FROM ubuntu:24.04

# Set the name of the image
LABEL name="odoo"

# Download odoo - I do this first for dev caching reasons
RUN apt update && apt upgrade -y
RUN apt install -y  \
	git               \
	python3           \
	python3-pip       \
	postgresql        \
	postgresql-client
COPY odoo_source/ /odoo
#RUN git clone https://github.com/odoo/odoo.git /odoo

# Clone and build
RUN /odoo/setup/debinstall.sh
COPY odoo.conf /odoo/odoo.conf

# Run
WORKDIR /odoo
ENTRYPOINT ["python3", "odoo-bin", "--addons-path=addons", "-d" , "$DB_USER"]

